id: P009465
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 19:40:03.984502
source_metadata:
  id: bdr:W21871
  title: རི་ཆོས་ངེས་དོན་རྒྱ་མཚོ་ཞེས་བྱ་བ་མཐར་ཐུག་ཐུན་མོང་མ་ཡིན་པའི་མན་ངག
  author: ''
  volumes:
    ca3e0a1936cf419e9ab60f47d412e7af:
      image_group_id: I4205
      title: ''
      volume_number: 1
      total_pages: 483
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
